version: '3'

services:
  app:
    image: bitwalker/alpine-elixir-phoenix
    volumes:
      - .:/opt/app
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    command: bash

  db:
    image: postgres
    environment:
      - POSTGRES_DB=b2ml_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db_test:
    image: postgres
    environment:
      - POSTGRES_DB=b2ml_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
